[WIP] feat: Support to Many Relationshipg
boazpoolman/strapi-plugin-sitemap pull request #139
Opened 2023-10-10 00:53 UTC by candidosales

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2023-10-10 02:09 UTC, candidosales commented on server/services/pattern.js
> +  fields = fields.map((field) => field.replace(/^.|.$/g, "")); // Strip [] from string. // PR - Simplify regex
Simplify regex

2023-10-10 02:09 UTC, candidosales commented on server/services/pattern.js
> +  let fields = pattern.match(/(?<=\/)(\[.*?\])(?=\/|$)/g); // Get all substrings between [] as array. // PR - Now it works with [value[0].field]
Now it works with [value[0].field]

2023-10-10 02:16 UTC, candidosales commented
@boazpoolman , could you review it? 😃

2023-10-10 05:56 UTC, boazpoolman reviewed
Just basing this question off of your screenrecording;

Is it possible to select different indexes in the array? For example `[relation[1].field]`

2023-10-10 09:48 UTC, boazpoolman commented
I would suggest solving that in this PR.
It's an essential feature when we introduce the relation array in url patterns.

2023-10-10 10:00 UTC, candidosales commented
@boazpoolman , it's fixed in my latest commit 😃

2023-10-10 10:04 UTC, candidosales commented
@boazpoolman , it's ready to review it

2023-10-10 10:06 UTC, boazpoolman commented
Great. I'll review as soon as I've got the time!

2023-10-14 16:10 UTC, boazpoolman requested changes
The eslint job is still failing.

Also it's very hard to review this PR because you've auto-fixed the files based on some prettier config that does not originate from the plugin.

It would be amazing if you could revert all those changes so that the diff of this PR is simply the code needed to implement the Many to Many relation feature.

2023-10-18 02:26 UTC, candidosales commented
@boazpoolman It's ready to review.

The changes are:

- `getAllowedFields`added support to showing fields with relationship ManyToMany;
- `getFieldsFromPattern` updated the Regex to support array fields;
- `resolvePattern`added support to interact with array values and your specific indexes;

Now, it's easier to review it.

2023-10-24 01:23 UTC, candidosales commented
@boazpoolman , could you review it?

2023-10-24 16:36 UTC, boazpoolman requested changes
For starters:
Thanks @candidosales for submitting this PR.

I've reviewed it and I'm having some issues.

1. If I use a `toOne` relation I see the dynamic value I can insert into the pattern (e.g. [category.id]). But if I add a `toMany` relation I don't see the field in the pattern description.
2. If I add the dynamic value anyways (e.g. [category[0].id]) and I try to save I get an internal server error.

Please see my video in which you can witness these two issues:

https://github.com/boazpoolman/strapi-plugin-sitemap/assets/9551934/44b0e259-5de5-4c63-8c9f-69cc53949951

2023-10-25 15:38 UTC, candidosales commented
@boazpoolman , great! Thanks for reviewing it!

I'll take a look.

2024-03-13 09:33 UTC, boazpoolman commented
Hi @candidosales 

Have you been able to look at my feedback?

2024-03-15 21:26 UTC, candidosales commented
Hi @boazpoolman , I didn't have time yet to improve it. Sorry about that. Many things are happening.

2024-07-01 17:45 UTC, Convolva commented
Hi, I think this is a much needed functionality. Is there any timeline for when we can have this feature @candidosales ?

Usually collection types like 'Blogs' and 'categories' tend to have a many to many relationship with the URL structure changing for the category and the blog. So this feature could be really helpful for those kinds of setup.

cc: @boazpoolman

2024-07-18 01:57 UTC, candidosales commented
Finally, I have time to take a look. @boazpoolman, could you review it?

2024-07-22 19:32 UTC, MSACC requested changes
We have tested the new code you provided us and we still get an internal server error. We hope you can fix. We get the error `error: Cannot read properties of null (reading '0')
TypeError: Cannot read properties of null (reading '0')` as previewed in the video @boazpoolman previously sent.

Greetings, Mathijs from PluginPal

2024-07-22 22:43 UTC, candidosales commented
@MSACC, could you share a video showing the issue? I would like to replicate

2024-07-28 11:50 UTC, boazpoolman commented
Mathijs experienced the same issues I did when I tested it.
I posted a video of it back then, [see my comment](https://github.com/pluginpal/strapi-plugin-sitemap/pull/139#pullrequestreview-1695392255).

2024-09-17 17:44 UTC, renatosilvarosa commented
@candidosales, this is a useful feature, and I also have this use case in a project I'm working on. Would you like some help finishing this PR?

2025-11-23 16:40 UTC, candidosales commented
@renatosilvarosa I've implemented the feature in the new version of the plugin; it's ready for review.

https://github.com/pluginpal/strapi-webtools/pull/355

2025-11-24 23:55 UTC, closed without merging