Feature/161 hreflang x default tag
boazpoolman/strapi-plugin-sitemap pull request #162
Opened 2024-03-09 19:01 UTC by RomainGueffier

### What does it do?

Add an additional link tag with hreflang x-default to improve locale detection fallback.
Add in settings form a select to save user preferences with 3 options:
- Disabled
- Default language pathname
- Other
When last option is selected, an extra text input field shows up to put a custom url.
Add translations for English and French
Extend default Test collection to add `slug` field in order to have better use cases to try feature.

### Why is it needed?

Improve SEO.

### How to test it?

Run strapi with plugin installed. Open Sitemap plugin settings.

Outputs:

1. Disabled

<img width="1616" alt="disabled (default)" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/71011271/613d1b39-80ca-4aed-9aae-e351f41eb436">

2. Default Locale

<img width="1607" alt="default-locale (bundles)" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/71011271/de26d99f-43f6-4bc1-9c32-b954ba9ecb55">

3. Other

<img width="1568" alt="Other (custom)" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/71011271/48fa8062-fc24-48d7-b11f-7cdf5e5ccd87">

### Related issue(s)/PR(s)

Closes #161 

### Tasks:

- [ ] add more translations ?
- [ ] can't find how to update docs via `yarn docs:generate` mentioned in CONTRIBUTING.md.
- [ ] improve labels and descriptions to help users understand what it does and SEO risks.

> ⚠️ `yarn develop / yarn playground:develop` did not update admin UI on save, whereas server was ok. Is it normal ? I needed to restart playground on each UI changes.

2024-03-10 16:08 UTC, boazpoolman requested changes
Thanks for this PR @RomainGueffier.
Functionally it works perfect!

I just have a couple remarks on your code.
If you could implement those changes I'll get this merged and released asap :)

2024-03-10 16:08 UTC, boazpoolman commented on server/services/core.js
> +    // find url with default locale in generated bundle
We only have to fetch the defaultLocale if the setting is actually set to 'default-locale'. Saves on some unnecessary queries.
```suggestion

  if (config.defaultLanguageUrlType === 'default-locale') {
    const { getDefaultLocale } = strapi.plugin('i18n').service('locales');
    const defaultLocale = await getDefaultLocale();
  
    // find url with default locale in generated bundle
```

2024-03-10 16:08 UTC, boazpoolman commented on admin/src/tabs/Settings/index.jsx
> +          </SingleSelectOption>
Could you abstract these `defaultLanguageUrlType` values to the `admin/config/constants.js` file?

Something like:

```
export const DEFAULT_LANGUAGE_URL_TYPE_DEFAULT_LOCALE = 'default-locale';
export const DEFAULT_LANGUAGE_URL_TYPE_OTHER = 'other';
```

Then everywhere these values are referenced you can use those constants.

2024-03-10 16:12 UTC, boazpoolman commented
> ⚠️ yarn develop / yarn playground:develop did not update admin UI on save, whereas server was ok. Is it normal ? I needed to restart playground on each UI changes.

You can run `yarn playground:develop --watch-admin` to make sure the admin also updates on save.

> can't find how to update docs via yarn docs:generate mentioned in CONTRIBUTING.md.

Sorry. Those `yarn docs:` commands are outdated and should be removed from the `package.json`

2024-03-13 06:54 UTC, RomainGueffier commented on admin/src/translations/fr.json
> +}
hehe I was going to offer my translation's services in another PR 😄 but if you want I can do it here

2024-03-13 09:30 UTC, merged